config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#index', as: :tasks

  get    "tasks/new", to: "tasks#new", as: :new_task
  post   "tasks", to: "tasks#create"

  get 'tasks/:id/edit', to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update"

  get 'tasks/:id', to: "tasks#show", as: :task

  delete "tasks/:id", to: "tasks#destroy"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task.id)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h2>Update task</h2>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <br><br>
  <%= f.label :details %>
  <%= f.text_field :details %>

  <br><br>
  <%= f.label :completed %>
  <%= f.check_box :completed %>

  <br><br>
  <%= f.submit %>
<% end %>
<br><br>

<%= link_to "Back to list", tasks_path %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

<% @tasks.each do |task| %>
  <ul>
  <p><% if task.completed %>
    <input type="checkbox" name="task" checked  disabled = "disabled">
  <%else%>
    <input type="checkbox" name="task" unchecked  disabled = "disabled">
  <%end%>
    <%= link_to task.title, task_path(task)%></p>
    <br>
    <%= link_to "Destroy!" %>
 </ul>
<% end %>

<br>

<%= link_to "Create a new dream", new_task_path %>

app/views/tasks/new.html.erb
<h2>new task</h2>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_area :details %>

  <%= f.submit %>
<% end %>

<br>

<%= link_to "Back to list", tasks_path %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p><%= @task.details %></p>


<% if @task.completed %>
  <input type="checkbox" name="task" checked>
<%else%>
  <input type="checkbox" name="task" unchecked >
<%end%>

<br><br>

<%= link_to "Back to list", tasks_path %>

<br><br>
<%= link_to "Update it!", edit_task_path %>